# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c51cecf82a7834b1ef8b6e3bb1f91837497537e66d7782333a664b9b34b2e090315266ae865983121f0a1f2cffd5513d80a9562fa7364ff33ea8a5a573c2ec

test:
  secret_key_base: e868ff621e4dd425bc9da426eb9c5925ba1cd45b94833f6e195ed4d82cf7645f73dcfd50ccb4046693d5c2b237cf22ca5748267706c86578d80ec45815299c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
